trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: 'grcneto/unyleya_devops'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build e push da imagem
  jobs:
  - job: BuildPush
    displayName: Docker build and push
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build e push para o Docker Hub
      inputs:
        containerRegistry: 'dockerhub-unyleya'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest